# config.yaml
input_dir: "/home/hellern/isilon/data/weaver_projects/request_176"
output_base_dir: "/home/hellern/isilon/data/weaver_projects/request_176_deid"
csv_output_manifest: "/home/hellern/isilon/data/weaver_projects/request_176_deid_log.csv"
manifest_path: "/home/hellern/isilon/data/weaver_projects/request_176_deid_manifest.csv"
redaction_mode: "Smart"
